database:
    username: "OGROUCH"
    password: "SECR3TPASSWORD"
    host: >
            (DESCRIPTION =
                    (ADDRESS = (PROTOCOL = TCP)
                               (HOST = servername.myschool.edu)
                               (PORT = 1521)
                    )
                        (CONNECT_DATA = (SERVER = DEDICATED)
                                    (SID = dbname)
                    )
            )